config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages
  resources :groups do
    resources :messages
    resources :group_users
  end
  root to: 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :group, required: false

  validate :user_has_rights

  def user_has_rights
    errors.add(:base, 'Not allowed') unless author.groups.include?(group)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :messages, foreign_key: :author_id
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/group_users_controller.rb
class GroupUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_group

  def create
    @group_user = GroupUser.create!(
      user_id: params[:user_id],
      group_id: @group.id
    )
    redirect_to @group_user.group
  rescue ActiveRecord::RecordNotFound
    render 'errors/404', status: 404
  end

  private

  def find_group
    @group = current_user.groups.find(params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.valid?
      @group.save
      @group.group_users.create!(user: current_user)

      redirect_to @group
    else
      render :new
    end
  end

  def show
    @group = current_user.groups.find(params[:id])
    @uninvited = User.where.not(id: @group.users.pluck(:id))
  rescue ActiveRecord::RecordNotFound
    render 'errors/404', status: 404
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    redirect_to messages_path if user_signed_in?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  MESSAGE_CHANNEL_PREFIX = 'chat_channel_'.freeze

  before_action :find_group

  def index
    @message = Message.new(group_id: @group.try(:id))

    @messages = Message.includes(:author).where("created_at > ?", 1.week.ago)
    if @group.present?
      @messages = @messages.where(group_id: @group.id)
    else
      @messages = @messages.where(group_id: nil)
    end
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.valid?
      @message.save
      ActionCable.server.broadcast "#{MESSAGE_CHANNEL_PREFIX}#{@message.group_id}", {
        message: @message.body,
        author: @message.author.email,
        timestamp: @message.created_at.strftime('%b %a %d, %H:%M')
      }
    else
      render json: { errors: @message.errors.full_messages.join(', ') }, status: 422
    end
  end

  protected

  def find_group
    @group = current_user.groups.find(params[:group_id]) if params[:group_id].present?
  end

  def message_params
    params.require(:message).permit(:body, :group_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/group_users/create.js.haml
:plain
  alert('User successfully invited')

app/views/groups/_form.html.haml
= form_for @group do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.submit 'Save', class: 'btn btn-primary'

app/views/groups/_group.html.haml
%p
  = link_to group.name, group

app/views/groups/index.html.haml
%h3 Groups
= link_to 'New Group', new_group_path, class: 'btn btn-primary'


= render @groups

app/views/groups/new.html.haml
%h3 New Group

= render 'form'

app/views/groups/show.html.haml
%h3= @group.name

.members-container
  %strong Members
  - @group.group_users.each do |group_user|
    %p= group_user.user.email

- if @uninvited.count.positive?
  .invite-container
    %strong Members
    - @uninvited.each do |user|
      %p= link_to user.email, group_group_users_path(@group.id, user_id: user.id), method: :post

= link_to 'Group Chat Room', group_messages_path(@group)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FonixChat
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css', intetrity: 'sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3', crossorigin: 'anonymous'
    = javascript_include_tag '//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js', integrity: 'sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p', crossorigin: 'anonymous'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/navbar'
    .container-fluid
      .row
        .col-md-12
          = yield

app/views/main/index.html.haml
%h1 Welcome

app/views/messages/create.js.haml
:plain
  $('#message_body').val('')

app/views/messages/index.html.haml
%h1 Messages

#messages_container.messages-container.container-fluid
  - @messages.each do |message|
    .message-container.row
      .body.col-md-10
        %strong
          = message.author.email
        %p= message.body
      .timestamp.col-md-2.right-aligned
        = message.created_at.strftime('%b %a %d, %H:%M')

  .message-form-container.row
    .col-md-12
      = form_for @message, remote: true do |f|
        = f.hidden_field :group_id
        = f.text_field :body
        = f.submit "Send"

:javascript
  window.group_id = '#{@group.try(:id)}'
  console.log(window.group_id)

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    = link_to 'Fonix Chat', root_path, class: 'navbar-brand'
    %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNav", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      %ul.navbar-nav
        - if user_signed_in?
          %li.nav-item
            = link_to "Hello, #{current_user.email}", root_path, class: 'nav-link'
          %li.nav-item
            = link_to "Groups", groups_path, class: 'nav-link'
          %li.nav-item
            = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          %li.nav-item
            = link_to 'Register', new_user_registration_path, class: 'nav-link'
          %li.nav-item
            = link_to 'Log in', new_user_session_path, class: 'nav-link'